export default {
    // Todos 
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    SET_DAILY: "SET_DAILY",
    MOVE_TODO_INDEX: "MOVE_TODO_INDEX",
    MOVE_TODO_TOP: "MOVE_TODO_TOP",
    MOVE_TODO_BOTTOM: "MOVE_TODO_BOTTOM",
    // Finance
    SET_PRICE: "SET_PRICE",
    // Finance Block
    SET_PRODUCT: "SET_PRODUCT",
    // Journal
    ADD_ENTRY: "ADD_ENTRY",
    REMOVE_ENTRY: "REMOVE_ENTRY",
    EDIT_ENTRY: "EDIT_ENTRY",
};